# Generated by Django 3.2.13 on 2022-09-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatourclientssay',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
