# Generated by Django 3.2.13 on 2022-09-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_whatourclientssay_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
