# Generated by Django 3.2.13 on 2022-09-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_portfolio_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdesign',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
