# Generated by Django 3.2.13 on 2022-09-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_projectdesign_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='similiar_projects',
            field=models.ManyToManyField(related_name='similiar_projects', to='app.ProjectType'),
        ),
    ]
