# Generated by Django 3.2.13 on 2022-09-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_portfolio_similiar_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='similiar_projects',
        ),
    ]
