# Generated by Django 3.2.13 on 2022-09-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_portfolio_similiar_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourwork',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
