# Generated by Django 3.2.13 on 2022-09-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_ourwork_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleacall',
            name='date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduleacall',
            name='time',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
