# Generated by Django 3.2.13 on 2022-09-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220912_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceoffer',
            name='file',
        ),
    ]
