# Generated by Django 3.2.13 on 2022-09-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_priceoffer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceoffer',
            name='file',
            field=models.FileField(blank=True, upload_to='project-files/price-offer'),
        ),
        migrations.AlterField(
            model_name='scheduleacall',
            name='date',
            field=models.DateField(),
        ),
    ]
