# Generated by Django 3.2.13 on 2022-09-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220912_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceoffer',
            name='file',
        ),
        migrations.AlterField(
            model_name='scheduleacall',
            name='date',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
